# Generated by Django 3.1.4 on 2020-12-30 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=25, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='media/product')),
                ('description', models.TextField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.mainproduct')),
            ],
        ),
    ]
