# Generated by Django 3.1.4 on 2020-12-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listtitle',
            name='main_title',
        ),
        migrations.AlterField(
            model_name='listtitle',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
