# Generated by Django 3.1.4 on 2021-01-06 05:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 5, 5, 39, 969021, tzinfo=utc)),
        ),
    ]
