# Generated by Django 3.1.4 on 2021-01-06 15:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210106_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadListTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('title_del', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_list', to='main.listtitle')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='list_title',
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 15, 17, 39, 647161, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ListProduct',
        ),
    ]
