# Generated by Django 3.1.4 on 2021-01-06 15:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210106_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlisttitle',
            name='product_q',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='test_field', to='main.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 15, 39, 43, 499619, tzinfo=utc)),
        ),
    ]
