# Generated by Django 3.1.4 on 2021-01-07 16:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210107_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 16, 56, 52, 962212, tzinfo=utc)),
        ),
    ]
